version: "3.7"
networks:
  wisefee-network-inner:
    driver: bridge
  wisefee-network-outer:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - wisefee-database
      - wisefee-redis
      - wisefee-app
    networks:
      - wisefee-network-outer

  wisefee-app:
    image: sjh9708/devserver-wisefee-app5:latest
    restart: always        #컨테이너 재실행
    depends_on: #database service가 실행된 이후에 실행
      - wisefee-database
      - wisefee-redis
#    ports:
#      - 8080:8080
    expose:
      - 8080
    container_name: wisefee-app-dev-deploy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://wisefee-database-dev-deploy:3306/wisefee-database?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_REDIS_HOST: wisefee-redis-dev-deploy  # Redis 호스트 이름 (컨테이너 이름)
      SPRING_REDIS_PORT: 6379  # Redis 기본 포트
    volumes:
      - ./volumes/storage/upload:/app/wisefee/storage/upload
      - ./volumes/log:/app/wisefee/log
    networks:
      - wisefee-network-inner
      - wisefee-network-outer

  wisefee-database:
#    platform: linux/x86_64
    image: mariadb:10.11.2
    container_name: wisefee-database-dev-deploy
    environment:
      MYSQL_DATABASE: "wisefee-database"
      MYSQL_ROOT_PASSWORD: "1111"
    expose:
      - 3306
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    networks: #사용할 네트워크 지정
      - wisefee-network-inner


  wisefee-redis: # container name
    image: redis:6.2.6-alpine
    expose:
      - 6379
    container_name: wisefee-redis-dev-deploy
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: # 마운트할 볼륨 설정
      - ./volumes/redis/data:/data
      - ./volumes/redis/conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - wisefee-network-inner

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wisefee-phpmyadmin
    environment:
      PMA_HOST: wisefee-database-dev-deploy
      PMA_USER: root
      PMA_PASSWORD: 1111
    ports:
      - '9090:9090'
    networks:
      - wisefee-network-inner

