version: "3.7"
networks:
  wisefee-network-inner:
    driver: bridge
  wisefee-network-outer:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - wisefee-redis
      - wisefee-app
    networks:
      - wisefee-network-outer

  wisefee-app:
    image: sjh9708/wisefee-app:latest
    restart: always        #컨테이너 재실행
    depends_on: #database service가 실행된 이후에 실행
      - wisefee-redis
#    ports:
#      - 8080:8080
    expose:
      - 8080
    container_name: wisefee-app-dev-deploy
    environment:
      SPRING_REDIS_HOST: wisefee-redis-dev-deploy  # Redis 호스트 이름 (컨테이너 이름)
      SPRING_REDIS_PORT: 6379  # Redis 기본 포트
    volumes:
      - ./volumes/log:/app/wisefee/log
    networks:
      - wisefee-network-inner
      - wisefee-network-outer

  wisefee-redis: # container name
    image: redis:6.2.6-alpine
    expose:
      - 6379
    container_name: wisefee-redis-dev-deploy
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: # 마운트할 볼륨 설정
      - ./volumes/redis/data:/data
      - ./volumes/redis/conf:/usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - wisefee-network-inner